Add TailwindCss Preset
sixlive/laravel-preset pull request #1
Opened 2019-02-02 19:50 UTC by simoebenhida

User can confirm if he wants to add Tailwindcss or Not

2019-02-14 14:36 UTC, sixlive commented
I'm down for this! I pushed some major updates and refactors to the Preset. If you're keen on updating this PR to match that I would be willing to merge.

2019-02-14 14:40 UTC, sixlive submitted a review, later dismissed
I'm thinking if we opt for the tailwind installation we should also just go ahead and run the the following as a task:

* `yarn install`
* `yarn tailwind init`
* `yarn dev`

2019-02-14 14:40 UTC, sixlive commented on src/stubs/webpack.mix.js
> +      require('tailwindcss')(/* './path/to/tailwind.js' */),
We should fill this value in and assume that its in the `base_path()`

2019-02-14 14:42 UTC, sixlive requested changes
I'm thinking if we opt for the tailwind installation we should also just go ahead and run the the following as a task:

* `yarn install`
* `yarn tailwind init`
* `yarn dev`

2019-02-18 00:01 UTC, simoebenhida commented
Here u go I pulled the new changes and added a task for each command above. Let me know what you think 👍

2019-02-18 17:42 UTC, sixlive requested changes
This is looking awesome. Just a few changes and we should be good.

2019-02-18 17:42 UTC, sixlive commented on src/Preset.php
> +            static::addTailwindcss($this->command);
```suggestion
           $this->command->task('Install Tailwindcss', function () {
               TailwindPreset::install();
           });
```

2019-02-18 17:42 UTC, sixlive commented on src/Preset.php
> +        if($this->command->confirm('Install Tailwindcss', true)) {
```suggestion
        if($this->command->confirm('Install Tailwindcss?', true)) {
```

2019-02-18 17:42 UTC, sixlive commented on src/Preset.php
> +                $this->runCommand('yarn install');
```suggestion
                $this->runCommand('yarn tailwind init');
```

2019-02-18 17:42 UTC, sixlive commented on src/Preset.php
> +    private function addTailwindcss()
We can remove this method since we are adding the task for it above.

2019-02-18 18:51 UTC, sixlive requested changes
Minor wording changes

2019-02-18 18:51 UTC, sixlive commented on src/Preset.php
> +            $this->command->task('yarn install', function () {
```suggestion
            $this->command->task('Install node dependencies with Yarn', function () {
```

2019-02-18 18:51 UTC, sixlive commented on src/Preset.php
> +            $this->command->task('yarn dev', function () {
```suggestion
            $this->command->task('Run node dev build with Yarn', function () {
```

2019-02-19 13:53 UTC, simoebenhida commented
Awesome !! thanks for your reviews. We should that often 😄

2019-02-19 14:18 UTC, sixlive approved these changes

2019-02-19 14:18 UTC, merged